<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ContactService.cs~RF4f74b6a.TMP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConnectSea.Crud.Domain\ConnectSea.Crud.Domain.csproj" />
  </ItemGroup>

</Project>
