// <auto-generated />
using System;
using ConnectSea.Crud.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConnectSea.Crud.Infra.Migrations
{
    [DbContext(typeof(DbCtx))]
    partial class DbCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConnectSea.Crud.Domain.Entity.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Eta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Etb")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Etd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Porto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("escalas", (string)null);
                });

            modelBuilder.Entity("ConnectSea.Crud.Domain.Entity.Manifesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PortoDestino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PortoOrigem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("manifestos", (string)null);
                });

            modelBuilder.Entity("ManifestoEscala", b =>
                {
                    b.Property<int>("ManifestoId")
                        .HasColumnType("integer");

                    b.Property<int>("EscalaId")
                        .HasColumnType("integer");

                    b.HasKey("ManifestoId", "EscalaId");

                    b.HasIndex("EscalaId");

                    b.ToTable("manifesto_escalas", (string)null);
                });

            modelBuilder.Entity("ManifestoEscala", b =>
                {
                    b.HasOne("ConnectSea.Crud.Domain.Entity.Escala", "Escala")
                        .WithMany("ManifestoEscalas")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConnectSea.Crud.Domain.Entity.Manifesto", "Manifesto")
                        .WithMany("ManifestoEscalas")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("ConnectSea.Crud.Domain.Entity.Escala", b =>
                {
                    b.Navigation("ManifestoEscalas");
                });

            modelBuilder.Entity("ConnectSea.Crud.Domain.Entity.Manifesto", b =>
                {
                    b.Navigation("ManifestoEscalas");
                });
#pragma warning restore 612, 618
        }
    }
}
